# Openstack
mod 'keystone',     :git => 'https://github.com/openstack/puppet-keystone',     :ref => 'victoria-eol'
mod 'glance',       :git => 'https://github.com/openstack/puppet-glance',       :ref => 'victoria-eol'
mod 'swift',        :git => 'https://github.com/openstack/puppet-swift',        :ref => 'victoria-eol'
mod 'cinder',       :git => 'https://github.com/openstack/puppet-cinder',       :ref => 'victoria-eol'
mod 'nova',         :git => 'https://github.com/openstack/puppet-nova',         :ref => 'victoria-eol'
mod 'ironic',       :git => 'https://github.com/openstack/puppet-ironic',       :ref => 'victoria-eol'
mod 'placement',    :git => 'https://github.com/openstack/puppet-placement',    :ref => 'victoria-eol'
mod 'neutron',      :git => 'https://github.com/openstack/puppet-neutron',      :ref => 'victoria-eol'
mod 'vswitch',      :git => 'https://github.com/openstack/puppet-vswitch',      :ref => 'victoria-eol'
mod 'horizon',      :git => 'https://github.com/openstack/puppet-horizon',      :ref => 'victoria-eol'
mod 'openstacklib', :git => 'https://github.com/openstack/puppet-openstacklib', :ref => 'victoria-eol'
mod 'cloudkitty',   :git => 'https://github.com/openstack/puppet-cloudkitty',   :ref => 'victoria-eol'
mod 'designate',    :git => 'https://github.com/openstack/puppet-designate' ,   :ref => 'victoria-eol'
mod 'oslo',         :git => 'https://github.com/openstack/puppet-oslo',         :ref => 'victoria-eol'

mod 'puppetlabs/apache',       :git => 'https://github.com/puppetlabs/puppetlabs-apache',     :ref => 'v12.1.0'
mod 'puppetlabs/apt',          :git => 'https://github.com/puppetlabs/puppetlabs-apt',        :ref => 'v7.7.1'
mod 'puppetlabs/concat',       :git => 'https://github.com/puppetlabs/puppetlabs-concat',     :ref => '5.3.0' # '2.2.1'
mod 'puppetlabs/firewall',     :git => 'https://github.com/puppetlabs/puppetlabs-firewall',   :ref => '1.8.2'
mod 'puppetlabs/inifile',      :git => 'https://github.com/puppetlabs/puppetlabs-inifile',    :ref => '2.5.0'
mod 'puppetlabs/mysql',        :git => 'https://github.com/puppetlabs/puppetlabs-mysql',      :ref => 'v10.10.0'
mod 'puppetlabs/postgresql',   :git => 'https://github.com/puppetlabs/puppetlabs-postgresql', :ref => 'v6.10.2'
mod 'puppetlabs/resource_api', :git => 'https://github.com/eb4x/puppet-resource_api',         :ref => 'stable/1.9'
mod 'puppetlabs/rsync',        :git => 'https://github.com/puppetlabs/puppetlabs-rsync',      :ref => '1.2.0'
mod 'puppetlabs/stdlib',       :git => 'https://github.com/puppetlabs/puppetlabs-stdlib',     :ref => '5.2.0'
mod 'puppetlabs/translate',    :git => 'https://github.com/puppetlabs/puppetlabs-translate',  :ref => '1.2.0'
mod 'puppetlabs/xinetd',       :git => 'https://github.com/puppetlabs/puppetlabs-xinetd',     :ref => '1.5.0'

mod 'voxpupuli/archive',      :git => 'https://github.com/voxpupuli/puppet-archive',      :ref => 'v3.2.1'
mod 'voxpupuli/git_resource', :git => 'https://github.com/voxpupuli/puppet-git_resource', :ref => 'v1.0.2'
mod 'voxpupuli/kmod',         :git => 'https://github.com/voxpupuli/puppet-kmod',         :ref => '2.5.0' #'v4.0.1'
mod 'voxpupuli/rabbitmq',     :git => 'https://github.com/voxpupuli/puppet-rabbitmq',     :ref => 'v8.5.0'
mod 'voxpupuli/systemd',      :git => 'https://github.com/voxpupuli/puppet-systemd',      :ref => '2.12.0'

mod 'foreman/dns', :git => 'https://github.com/theforeman/puppet-dns',          :ref => '5.4.0'
mod 'ipaclient',   :git => 'https://github.com/joshuabaird/puppet-ipaclient',   :ref => '2.5.2'
mod 'memcached',   :git => 'https://github.com/saz/puppet-memcached',           :ref => 'v3.4.0'
mod 'powerdns',    :git => 'https://github.com/antonlindstrom/puppet-powerdns', :ref => '0.0.5'
mod 'sysctl',      :git => 'https://github.com/duritong/puppet-sysctl',         :ref => 'v0.0.12'
